[package]
name = "cal7tor"
version = "0.9.0"
authors = ["Mylloon"]
edition = "2021"
description = "Timetable extractor for the Paris Cité master's degree in IT"
readme = "README.md"
repository = "https://git.mylloon.fr/Anri/cal7tor"
keywords = ["scrape", "calendar"]
publish = false
license = "AGPL-3.0-or-later"

[dependencies]
reqwest = { version = "0.11" }
tokio = { version = "1.35", features = ["full"] }
scraper = "0.18"
regex = "1.10"
chrono = "0.4.31"
ics = "0.5"
uuid = { version = "1.6", features = ["v4", "fast-rng"] }
clap = { version = "4.4", features = ["derive"] }
dialoguer = "0.11"
