[package]
name = "cal7tor"
version = "0.5.0"
authors = ["Mylloon"]
edition = "2021"
description = "Timetable extractor for the Paris Cité master's degree in IT"
readme = "README.md"
repository = "https://git.mylloon.fr/Anri/cal7tor"
keywords = ["scrape", "calendar"]
publish = false
license = "AGPL-3.0-or-later"

[dependencies]
reqwest = { version = "0.11" }
tokio = { version = "1.32", features = ["full"] }
scraper = "0.17"
regex = "1.9"
chrono = "0.4.28"
ics = "0.5"
uuid = { version = "1.4", features = ["v4", "fast-rng"] }
clap = { version = "4.4", features = ["derive"] }
